// © 2022 and later: Unicode, Inc. and others.
// License & terms of use: http://www.unicode.org/copyright.html
//
// Internal static data tables used by uresbund.cpp
// WARNING: This file is mechanically generated by the CLDR-to-ICU tool
// (see tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/generator/ResourceFallbackCodeGenerator.java).
// DO NOT HAND EDIT!!!

#ifdef INCLUDED_FROM_URESBUND_CPP

// ======================================================================
// Default script table
const char scriptCodeChars[] =
    "Aghb\0Ahom\0Arab\0Armi\0Armn\0Avst\0Bali\0Bamu\0Batk\0Beng\0Bopo\0"
    "Brah\0Cakm\0Cans\0Cari\0Cham\0Cher\0Chrs\0Copt\0Cprt\0Cyrl\0Deva\0"
    "Egyp\0Elym\0Ethi\0Geor\0Gonm\0Goth\0Gran\0Grek\0Gujr\0Guru\0Hang\0"
    "Hani\0Hans\0Hant\0Hebr\0Hluw\0Hmnp\0Ital\0Java\0Jpan\0Jurc\0Kali\0"
    "Kana\0Khar\0Khmr\0Kits\0Knda\0Kore\0Lana\0Laoo\0Latf\0Latg\0Lepc\0"
    "Lina\0Linb\0Lisu\0Lyci\0Lydi\0Mand\0Mani\0Marc\0Medf\0Merc\0Mlym\0"
    "Modi\0Mong\0Mroo\0Mtei\0Mymr\0Narb\0Newa\0Nkoo\0Ogam\0Olck\0Orkh\0"
    "Orya\0Osge\0Ougr\0Pauc\0Phli\0Phnx\0Plrd\0Prti\0Rjng\0Rohg\0Runr\0"
    "Samr\0Sarb\0Saur\0Seal\0Sgnw\0Sidt\0Sinh\0Sogd\0Sora\0Soyo\0Syrc\0"
    "Tagb\0Takr\0Tale\0Talu\0Taml\0Tang\0Tavt\0Telu\0Tfng\0Thaa\0Thai\0"
    "Tibt\0Tnsa\0Toto\0Ugar\0Vaii\0Wcho\0Xpeo\0Xsux\0Yiii\0";

const char dsLocaleIDChars[] =
    "aaf\0aao\0aat\0ab\0abh\0abl\0abq\0abv\0acm\0acq\0acw\0acx\0adf\0"
    "adx\0ady\0ae\0aeb\0aec\0aee\0aeq\0afb\0agi\0agj\0agx\0ahg\0aho\0"
    "ahr\0aib\0aii\0aij\0ain\0aio\0aiq\0akk\0akv\0alk\0all\0alr\0alt\0"
    "alw\0am\0ams\0amw\0ani\0anp\0anq\0anr\0anu\0aot\0apc\0apd\0aph\0"
    "aqc\0ar\0arc\0arq\0ars\0ary\0arz\0as\0ase\0ask\0asr\0atn\0atv\0"
    "auj\0auz\0av\0avd\0avl\0awa\0awn\0axm\0ayh\0ayl\0ayn\0ayp\0az_IQ\0"
    "az_IR\0az_RU\0azb\0ba\0bal\0bap\0bax\0bbl\0bcq\0bdv\0bdz\0be\0"
    "bee\0bej\0bfb\0bfq\0bft\0bfu\0bfw\0bfy\0bfz\0bg\0bgc\0bgd\0bgn\0"
    "bgp\0bgq\0bgw\0bgx\0bha\0bhb\0bhd\0bhe\0bhh\0bhi\0bhj\0bhm\0bhn\0"
    "bho\0bht\0bhu\0bix\0biy\0bjf\0bjj\0bjm\0bkk\0blk\0blt\0bmj\0bn\0"
    "bns\0bo\0bph\0bpx\0bpy\0bqi\0bra\0brb\0brd\0brh\0brk\0bro\0brv\0"
    "brw\0brx\0bsh\0bsk\0bst\0btd\0btm\0btv\0bua\0bwe\0bxm\0bxu\0byh\0"
    "byn\0byw\0bzi\0cbn\0ccp\0cde\0cdh\0cdi\0cdj\0cdm\0cdn\0cdo\0cdz\0"
    "ce\0cgk\0chg\0chm\0chr\0chx\0cih\0cja\0cji\0cjm\0cjy\0ckb\0ckt\0"
    "clh\0clw\0cmg\0cna\0cnp\0cnu\0cog\0cop\0cpg\0cpx\0cr\0crh\0crj\0"
    "crk\0crl\0crm\0csh\0csj\0csp\0csw\0ctd\0ctg\0ctn\0ctt\0cty\0cu\0"
    "cuu\0cv\0czh\0czk\0daq\0dar\0dcc\0ddo\0def\0deh\0der\0dgl\0dhi\0"
    "dhn\0dho\0dhw\0dka\0dlg\0dmf\0dmk\0dml\0dng\0dnu\0dnv\0doi\0dox\0"
    "dre\0drq\0drs\0dry\0dso\0dty\0dub\0duh\0dus\0dv\0dwk\0dwz\0dz\0"
    "dzl\0ecr\0ecy\0egy\0eky\0el\0emg\0emu\0enf\0enh\0era\0esg\0esh\0"
    "ett\0eve\0evn\0fa\0fay\0faz\0fia\0fmu\0fub\0gan\0gaq\0gas\0gau\0"
    "gbj\0gbk\0gbl\0gbm\0gbz\0gdb\0gdo\0gdx\0gez\0ggg\0gha\0ghe\0gho\0"
    "ghr\0ght\0gig\0gin\0gjk\0gju\0gld\0glh\0glk\0gml\0gmv\0gmy\0goe\0"
    "gof\0goj\0gok\0gon\0got\0gra\0grc\0grr\0grt\0gru\0gu\0gvr\0gwc\0"
    "gwf\0gwt\0gyo\0gzi\0ha_CM\0ha_SD\0hac\0hak\0hak_TW\0har\0haz\0"
    "hbo\0hdy\0he\0hi\0hif\0hii\0hit\0hkh\0hlb\0hlu\0hmd\0hmj\0hmq\0"
    "hnd\0hne\0hnj\0hnm\0hno\0hoc\0hoh\0hoj\0how\0hoy\0hpo\0hrt\0hrz\0"
    "hsn\0hss\0htx\0hut\0huy\0huz\0hy\0hyw\0ii\0imy\0inh\0int\0ior\0"
    "iru\0isk\0itk\0itl\0iu\0iw\0ja\0jad\0jat\0jbe\0jbn\0jct\0jda\0"
    "jdg\0jdt\0jee\0jge\0ji\0jje\0jkp\0jml\0jna\0jnd\0jnl\0jns\0jog\0"
    "jpa\0jpr\0jrb\0juc\0jul\0jun\0juy\0jya\0jye\0ka\0kaa\0kap\0kaw\0"
    "kbd\0kbg\0kbu\0kby\0kca\0kcy\0kdq\0kdt\0ket\0kev\0kex\0key\0kfa\0"
    "kfb\0kfc\0kfd\0kfe\0kfg\0kfh\0kfi\0kfk\0kfm\0kfp\0kfq\0kfr\0kfs\0"
    "kfu\0kfx\0kfy\0kgj\0kgy\0khb\0khf\0khg\0khn\0kho\0kht\0khv\0khw\0"
    "kif\0kim\0kip\0kjg\0kjh\0kjl\0kjo\0kjp\0kjt\0kjz\0kk\0kk_AF\0"
    "kk_CN\0kk_IR\0kk_MN\0kkf\0kkh\0kkt\0kle\0klj\0klr\0km\0kmj\0kmz\0"
    "kn\0knn\0ko\0koi\0kok\0kpt\0kpy\0kqd\0kqy\0kra\0krc\0krk\0krr\0"
    "kru\0krv\0ks\0ksu\0ksw\0ksz\0ktb\0kte\0ktl\0ktp\0ku_AM\0ku_AZ\0"
    "ku_GE\0ku_IQ\0ku_IR\0ku_LB\0ku_TM\0kuf\0kum\0kv\0kva\0kvq\0kvt\0"
    "kvx\0kvy\0kwx\0kxf\0kxk\0kxm\0kxp\0ky\0ky_CN\0kyu\0kyv\0kyw\0"
    "kzq\0lab\0lad\0lae\0lah\0lbe\0lbf\0lbj\0lbm\0lbo\0lbr\0lcp\0lep\0"
    "lez\0lhm\0lhs\0lif\0lis\0lkh\0lki\0lmh\0lmn\0lo\0loy\0lpo\0lrc\0"
    "lrk\0lrl\0lsa\0lsd\0lss\0ltc\0luh\0luk\0luu\0luv\0luz\0lwl\0lwm\0"
    "lya\0lzh\0lzz_GE\0mag\0mai\0mby\0mde\0mdf\0mdx\0mdy\0mey\0mfa\0"
    "mfi\0mga\0mgp\0mhj\0mid\0mjl\0mjq\0mjr\0mjt\0mju\0mjv\0mjz\0mk\0"
    "mkb\0mke\0mki\0mkm\0ml\0mlf\0mn\0mn_CN\0mnc\0mni\0mnj\0mnp\0mns\0"
    "mnw\0mpz\0mr\0mra\0mrj\0mro\0mrr\0ms_CC\0mtm\0mtr\0mud\0muk\0"
    "mut\0muv\0muz\0mve\0mvf\0mvy\0mvz\0mwr\0mwt\0mww\0my\0mym\0myv\0"
    "myz\0mzb\0mzn\0nan\0nan_MO\0nan_TW\0nao\0ncd\0ncq\0ndf\0ne\0neg\0"
    "neh\0nei\0nev\0new\0ngt\0nio\0nit\0niv\0nli\0nll\0nlm\0nlx\0nmm\0"
    "nnp\0nod\0noe\0nog\0noi\0non\0nos\0npb\0nqo\0nrn\0nsd\0nsf\0nsk\0"
    "nst\0nsv\0nty\0ntz\0nwc\0nwx\0nyl\0nyq\0nyw\0oaa\0oac\0oak\0oar\0"
    "oav\0obm\0obr\0och\0odk\0oht\0oj\0ojs\0okm\0oko\0okz\0ola\0ole\0"
    "omk\0omp\0omr\0omx\0omy\0oon\0or\0ort\0oru\0orv\0os\0osa\0osc\0"
    "osd\0osi\0ota\0otb\0otk\0oty\0oui\0oyb\0pa\0pa_PK\0pal\0paq\0"
    "pbt\0pcb\0pce\0pcf\0pcg\0pch\0pci\0pcj\0peg\0peo\0pgd\0pgg\0pgl\0"
    "pgn\0phd\0phk\0phl\0phn\0pho\0phr\0pht\0phu\0phv\0phw\0pi_IN\0"
    "pi_LK\0pi_MM\0pi_TH\0pka\0pkr\0plk\0pll\0pmh\0pnt\0pnt_RU\0pnx\0"
    "prc\0prd\0prt\0prx\0ps\0psh\0psi\0pst\0psu\0pum\0pwo\0pwr\0pww\0"
    "pyx\0qxq\0raa\0rab\0raf\0rah\0raj\0rav\0rbb\0rdb\0rei\0rhg\0rji\0"
    "rjs\0rka\0rki\0rkt\0rmi\0rmt\0rmz\0rsk\0rtw\0ru\0rue\0rut\0rwr\0"
    "ryu\0sa\0sah\0sam\0sat\0saz\0sbn\0sbu\0sck\0scl\0scp\0sct\0scu\0"
    "scx\0sd\0sd_IN\0sdb\0sdf\0sdg\0sdh\0sdr\0sds\0sel\0sfm\0sgh\0"
    "sgj\0sgr\0sgt\0sgw\0sgy\0shd\0shi\0shm\0shn\0shu\0shv\0si\0sia\0"
    "sip\0siy\0siz\0sjc\0sjd\0sjp\0sjt\0skb\0skj\0skr\0sle\0smh\0smp\0"
    "smu\0smy\0soa\0sog\0soi\0sou\0spt\0spv\0sqo\0sqq\0sqt\0sr\0srb\0"
    "srh\0srx\0srz\0ssh\0sss\0sts\0stu\0stu_CN\0stv\0sty\0suz\0sva\0"
    "swb\0swi\0swv\0sxu\0syc\0syl\0syn\0syr\0syw\0ta\0tab\0taj\0tbk\0"
    "tcn\0tco\0tcx\0tcy\0tda\0tdb\0tdd\0tdg\0tdh\0te\0tes\0tg\0tg_PK\0"
    "tge\0tgf\0th\0the\0thf\0thi\0thl\0thm\0thq\0thr\0ths\0ti\0tig\0"
    "tij\0tin\0tjl\0tjo\0tkb\0tks\0tkt\0tmr\0tnv\0tov\0tpu\0tra\0trg\0"
    "trm\0trw\0tsd\0tsj\0tt\0tth\0tto\0tts\0ttz\0tvn\0twm\0txg\0txo\0"
    "tyr\0tyv\0ude\0udg\0udi\0udm\0ug\0ug_KZ\0ug_MN\0uga\0ugh\0ugo\0"
    "uk\0uki\0ulc\0unr\0unr_NP\0unx\0ur\0urk\0ush\0uum\0uz_AF\0uz_CN\0"
    "uzs\0vaa\0vaf\0vah\0vai\0vas\0vav\0vay\0vgr\0vjk\0vmd\0vmh\0wal\0"
    "wbk\0wbq\0wbr\0wle\0wly\0wme\0wne\0wni\0wsg\0wsv\0wtm\0wuu\0xag\0"
    "xal\0xan\0xas\0xco\0xcr\0xdq\0xhe\0xhm\0xis\0xka\0xkc\0xkf\0xkj\0"
    "xkk\0xkp\0xlc\0xld\0xly\0xmf\0xmn\0xmr\0xna\0xnr\0xpg\0xpi\0xpm\0"
    "xpr\0xrm\0xrn\0xsa\0xsd\0xsr\0xtq\0xua\0xub\0xuj\0xve\0xvi\0xwo\0"
    "xzh\0yai\0ybh\0ybi\0ydg\0yea\0yej\0yeu\0ygp\0yhd\0yi\0yig\0yih\0"
    "yin\0yiv\0ykg\0ykh\0yna\0ynk\0yoi\0yoy\0yrk\0ysd\0ysn\0ysp\0ysr\0"
    "ysy\0yud\0yue\0yue_CN\0yug\0yux\0ywq\0ywu\0zau\0zba\0zch\0zdj\0"
    "zeh\0zen\0zgb\0zgh\0zgm\0zgn\0zh\0zh_AU\0zh_BN\0zh_GB\0zh_GF\0"
    "zh_HK\0zh_ID\0zh_MO\0zh_PA\0zh_PF\0zh_PH\0zh_SR\0zh_TH\0zh_TW\0"
    "zh_US\0zh_VN\0zhd\0zkn\0zko\0zkt\0zkz\0zlj\0zln\0zlq\0zqe\0zrg\0"
    "zrp\0zum\0zwa\0zyg\0zyn\0zzj\0";

const int32_t defaultScriptTable[] = {
    0, 325,  // aaf -> Mlym
    4, 10,  // aao -> Arab
    8, 145,  // aat -> Grek
    12, 100,  // ab -> Cyrl
    15, 10,  // abh -> Arab
    19, 425,  // abl -> Rjng
    23, 100,  // abq -> Cyrl
    27, 10,  // abv -> Arab
    31, 10,  // acm -> Arab
    35, 10,  // acq -> Arab
    39, 10,  // acw -> Arab
    43, 10,  // acx -> Arab
    47, 10,  // adf -> Arab
    51, 550,  // adx -> Tibt
    55, 100,  // ady -> Cyrl
    59, 25,  // ae -> Avst
    62, 10,  // aeb -> Arab
    66, 10,  // aec -> Arab
    70, 10,  // aee -> Arab
    74, 10,  // aeq -> Arab
    78, 10,  // afb -> Arab
    82, 105,  // agi -> Deva
    86, 120,  // agj -> Ethi
    90, 100,  // agx -> Cyrl
    94, 120,  // ahg -> Ethi
    98, 5,  // aho -> Ahom
    102, 105,  // ahr -> Deva
    106, 10,  // aib -> Arab
    110, 490,  // aii -> Syrc
    114, 180,  // aij -> Hebr
    118, 220,  // ain -> Kana
    122, 350,  // aio -> Mymr
    126, 10,  // aiq -> Arab
    130, 585,  // akk -> Xsux
    134, 100,  // akv -> Cyrl
    138, 255,  // alk -> Laoo
    142, 325,  // all -> Mlym
    146, 100,  // alr -> Cyrl
    150, 100,  // alt -> Cyrl
    154, 120,  // alw -> Ethi
    158, 120,  // am -> Ethi
    161, 205,  // ams -> Jpan
    165, 490,  // amw -> Syrc
    169, 100,  // ani -> Cyrl
    173, 105,  // anp -> Deva
    177, 105,  // anq -> Deva
    181, 105,  // anr -> Deva
    185, 120,  // anu -> Ethi
    189, 45,  // aot -> Beng
    193, 10,  // apc -> Arab
    197, 10,  // apd -> Arab
    201, 105,  // aph -> Deva
    205, 100,  // aqc -> Cyrl
    209, 10,  // ar -> Arab
    212, 15,  // arc -> Armi
    216, 10,  // arq -> Arab
    220, 10,  // ars -> Arab
    224, 10,  // ary -> Arab
    228, 10,  // arz -> Arab
    232, 45,  // as -> Beng
    235, 460,  // ase -> Sgnw
    239, 10,  // ask -> Arab
    243, 105,  // asr -> Deva
    247, 10,  // atn -> Arab
    251, 100,  // atv -> Cyrl
    255, 10,  // auj -> Arab
    259, 10,  // auz -> Arab
    263, 100,  // av -> Cyrl
    266, 10,  // avd -> Arab
    270, 10,  // avl -> Arab
    274, 105,  // awa -> Deva
    278, 120,  // awn -> Ethi
    282, 20,  // axm -> Armn
    286, 10,  // ayh -> Arab
    290, 10,  // ayl -> Arab
    294, 10,  // ayn -> Arab
    298, 10,  // ayp -> Arab
    302, 10,  // az_IQ -> Arab
    308, 10,  // az_IR -> Arab
    314, 100,  // az_RU -> Cyrl
    320, 10,  // azb -> Arab
    324, 100,  // ba -> Cyrl
    327, 10,  // bal -> Arab
    331, 105,  // bap -> Deva
    335, 35,  // bax -> Bamu
    339, 125,  // bbl -> Geor
    343, 120,  // bcq -> Ethi
    347, 385,  // bdv -> Orya
    351, 10,  // bdz -> Arab
    355, 100,  // be -> Cyrl
    358, 105,  // bee -> Deva
    362, 10,  // bej -> Arab
    366, 105,  // bfb -> Deva
    370, 515,  // bfq -> Taml
    374, 10,  // bft -> Arab
    378, 550,  // bfu -> Tibt
    382, 385,  // bfw -> Orya
    386, 105,  // bfy -> Deva
    390, 105,  // bfz -> Deva
    394, 100,  // bg -> Cyrl
    397, 105,  // bgc -> Deva
    401, 105,  // bgd -> Deva
    405, 10,  // bgn -> Arab
    409, 10,  // bgp -> Arab
    413, 105,  // bgq -> Deva
    417, 105,  // bgw -> Deva
    421, 145,  // bgx -> Grek
    425, 105,  // bha -> Deva
    429, 105,  // bhb -> Deva
    433, 105,  // bhd -> Deva
    437, 10,  // bhe -> Arab
    441, 100,  // bhh -> Cyrl
    445, 105,  // bhi -> Deva
    449, 105,  // bhj -> Deva
    453, 10,  // bhm -> Arab
    457, 490,  // bhn -> Syrc
    461, 105,  // bho -> Deva
    465, 105,  // bht -> Deva
    469, 105,  // bhu -> Deva
    473, 105,  // bix -> Deva
    477, 105,  // biy -> Deva
    481, 490,  // bjf -> Syrc
    485, 105,  // bjj -> Deva
    489, 10,  // bjm -> Arab
    493, 550,  // bkk -> Tibt
    497, 350,  // blk -> Mymr
    501, 525,  // blt -> Tavt
    505, 105,  // bmj -> Deva
    509, 45,  // bn -> Beng
    512, 105,  // bns -> Deva
    516, 550,  // bo -> Tibt
    519, 100,  // bph -> Cyrl
    523, 105,  // bpx -> Deva
    527, 45,  // bpy -> Beng
    531, 10,  // bqi -> Arab
    535, 105,  // bra -> Deva
    539, 230,  // brb -> Khmr
    543, 105,  // brd -> Deva
    547, 10,  // brh -> Arab
    551, 10,  // brk -> Arab
    555, 550,  // bro -> Tibt
    559, 255,  // brv -> Laoo
    563, 240,  // brw -> Knda
    567, 105,  // brx -> Deva
    571, 10,  // bsh -> Arab
    575, 10,  // bsk -> Arab
    579, 120,  // bst -> Ethi
    583, 40,  // btd -> Batk
    587, 40,  // btm -> Batk
    591, 105,  // btv -> Deva
    595, 100,  // bua -> Cyrl
    599, 350,  // bwe -> Mymr
    603, 100,  // bxm -> Cyrl
    607, 335,  // bxu -> Mong
    611, 105,  // byh -> Deva
    615, 120,  // byn -> Ethi
    619, 105,  // byw -> Deva
    623, 545,  // bzi -> Thai
    627, 545,  // cbn -> Thai
    631, 60,  // ccp -> Cakm
    635, 530,  // cde -> Telu
    639, 105,  // cdh -> Deva
    643, 150,  // cdi -> Gujr
    647, 105,  // cdj -> Deva
    651, 105,  // cdm -> Deva
    655, 105,  // cdn -> Deva
    659, 170,  // cdo -> Hans
    663, 45,  // cdz -> Beng
    667, 100,  // ce -> Cyrl
    670, 550,  // cgk -> Tibt
    674, 10,  // chg -> Arab
    678, 100,  // chm -> Cyrl
    682, 80,  // chr -> Cher
    686, 105,  // chx -> Deva
    690, 105,  // cih -> Deva
    694, 10,  // cja -> Arab
    698, 100,  // cji -> Cyrl
    702, 75,  // cjm -> Cham
    706, 170,  // cjy -> Hans
    710, 10,  // ckb -> Arab
    714, 100,  // ckt -> Cyrl
    718, 10,  // clh -> Arab
    722, 100,  // clw -> Cyrl
    726, 485,  // cmg -> Soyo
    730, 550,  // cna -> Tibt
    734, 170,  // cnp -> Hans
    738, 535,  // cnu -> Tfng
    742, 545,  // cog -> Thai
    746, 90,  // cop -> Copt
    750, 145,  // cpg -> Grek
    754, 170,  // cpx -> Hans
    758, 65,  // cr -> Cans
    761, 100,  // crh -> Cyrl
    765, 65,  // crj -> Cans
    769, 65,  // crk -> Cans
    773, 65,  // crl -> Cans
    777, 65,  // crm -> Cans
    781, 350,  // csh -> Mymr
    785, 350,  // csj -> Mymr
    789, 170,  // csp -> Hans
    793, 65,  // csw -> Cans
    797, 400,  // ctd -> Pauc
    801, 45,  // ctg -> Beng
    805, 105,  // ctn -> Deva
    809, 515,  // ctt -> Taml
    813, 515,  // cty -> Taml
    817, 100,  // cu -> Cyrl
    820, 250,  // cuu -> Lana
    824, 100,  // cv -> Cyrl
    827, 170,  // czh -> Hans
    831, 180,  // czk -> Hebr
    835, 105,  // daq -> Deva
    839, 100,  // dar -> Cyrl
    843, 10,  // dcc -> Arab
    847, 100,  // ddo -> Cyrl
    851, 10,  // def -> Arab
    855, 10,  // deh -> Arab
    859, 45,  // der -> Beng
    863, 10,  // dgl -> Arab
    867, 105,  // dhi -> Deva
    871, 150,  // dhn -> Gujr
    875, 150,  // dho -> Gujr
    879, 105,  // dhw -> Deva
    883, 550,  // dka -> Tibt
    887, 100,  // dlg -> Cyrl
    891, 315,  // dmf -> Medf
    895, 10,  // dmk -> Arab
    899, 10,  // dml -> Arab
    903, 100,  // dng -> Cyrl
    907, 350,  // dnu -> Mymr
    911, 350,  // dnv -> Mymr
    915, 105,  // doi -> Deva
    919, 120,  // dox -> Ethi
    923, 550,  // dre -> Tibt
    927, 105,  // drq -> Deva
    931, 120,  // drs -> Ethi
    935, 105,  // dry -> Deva
    939, 385,  // dso -> Orya
    943, 105,  // dty -> Deva
    947, 150,  // dub -> Gujr
    951, 105,  // duh -> Deva
    955, 105,  // dus -> Deva
    959, 540,  // dv -> Thaa
    962, 385,  // dwk -> Orya
    966, 105,  // dwz -> Deva
    970, 550,  // dz -> Tibt
    973, 550,  // dzl -> Tibt
    977, 145,  // ecr -> Grek
    981, 95,  // ecy -> Cprt
    985, 110,  // egy -> Egyp
    989, 215,  // eky -> Kali
    993, 145,  // el -> Grek
    996, 105,  // emg -> Deva
    1000, 105,  // emu -> Deva
    1004, 100,  // enf -> Cyrl
    1008, 100,  // enh -> Cyrl
    1012, 515,  // era -> Taml
    1016, 130,  // esg -> Gonm
    1020, 10,  // esh -> Arab
    1024, 195,  // ett -> Ital
    1028, 100,  // eve -> Cyrl
    1032, 100,  // evn -> Cyrl
    1036, 10,  // fa -> Arab
    1039, 10,  // fay -> Arab
    1043, 10,  // faz -> Arab
    1047, 10,  // fia -> Arab
    1051, 105,  // fmu -> Deva
    1055, 10,  // fub -> Arab
    1059, 170,  // gan -> Hans
    1063, 385,  // gaq -> Orya
    1067, 150,  // gas -> Gujr
    1071, 530,  // gau -> Telu
    1075, 385,  // gbj -> Orya
    1079, 105,  // gbk -> Deva
    1083, 150,  // gbl -> Gujr
    1087, 105,  // gbm -> Deva
    1091, 10,  // gbz -> Arab
    1095, 385,  // gdb -> Orya
    1099, 100,  // gdo -> Cyrl
    1103, 105,  // gdx -> Deva
    1107, 120,  // gez -> Ethi
    1111, 10,  // ggg -> Arab
    1115, 10,  // gha -> Arab
    1119, 105,  // ghe -> Deva
    1123, 535,  // gho -> Tfng
    1127, 10,  // ghr -> Arab
    1131, 550,  // ght -> Tibt
    1135, 10,  // gig -> Arab
    1139, 100,  // gin -> Cyrl
    1143, 10,  // gjk -> Arab
    1147, 10,  // gju -> Arab
    1151, 100,  // gld -> Cyrl
    1155, 10,  // glh -> Arab
    1159, 10,  // glk -> Arab
    1163, 260,  // gml -> Latf
    1167, 120,  // gmv -> Ethi
    1171, 280,  // gmy -> Linb
    1175, 550,  // goe -> Tibt
    1179, 120,  // gof -> Ethi
    1183, 105,  // goj -> Deva
    1187, 105,  // gok -> Deva
    1191, 105,  // gon -> Deva
    1195, 135,  // got -> Goth
    1199, 105,  // gra -> Deva
    1203, 145,  // grc -> Grek
    1207, 10,  // grr -> Arab
    1211, 45,  // grt -> Beng
    1215, 120,  // gru -> Ethi
    1219, 150,  // gu -> Gujr
    1222, 105,  // gvr -> Deva
    1226, 10,  // gwc -> Arab
    1230, 10,  // gwf -> Arab
    1234, 10,  // gwt -> Arab
    1238, 105,  // gyo -> Deva
    1242, 10,  // gzi -> Arab
    1246, 10,  // ha_CM -> Arab
    1252, 10,  // ha_SD -> Arab
    1258, 10,  // hac -> Arab
    1262, 170,  // hak -> Hans
    1266, 175,  // hak_TW -> Hant
    1273, 120,  // har -> Ethi
    1277, 10,  // haz -> Arab
    1281, 180,  // hbo -> Hebr
    1285, 120,  // hdy -> Ethi
    1289, 180,  // he -> Hebr
    1292, 105,  // hi -> Deva
    1295, 105,  // hif -> Deva
    1299, 500,  // hii -> Takr
    1303, 585,  // hit -> Xsux
    1307, 10,  // hkh -> Arab
    1311, 105,  // hlb -> Deva
    1315, 185,  // hlu -> Hluw
    1319, 415,  // hmd -> Plrd
    1323, 50,  // hmj -> Bopo
    1327, 50,  // hmq -> Bopo
    1331, 10,  // hnd -> Arab
    1335, 105,  // hne -> Deva
    1339, 190,  // hnj -> Hmnp
    1343, 170,  // hnm -> Hans
    1347, 10,  // hno -> Arab
    1351, 105,  // hoc -> Deva
    1355, 10,  // hoh -> Arab
    1359, 105,  // hoj -> Deva
    1363, 165,  // how -> Hani
    1367, 105,  // hoy -> Deva
    1371, 350,  // hpo -> Mymr
    1375, 490,  // hrt -> Syrc
    1379, 10,  // hrz -> Arab
    1383, 170,  // hsn -> Hans
    1387, 10,  // hss -> Arab
    1391, 585,  // htx -> Xsux
    1395, 105,  // hut -> Deva
    1399, 180,  // huy -> Hebr
    1403, 100,  // huz -> Cyrl
    1407, 20,  // hy -> Armn
    1410, 20,  // hyw -> Armn
    1414, 590,  // ii -> Yiii
    1417, 290,  // imy -> Lyci
    1421, 100,  // inh -> Cyrl
    1425, 350,  // int -> Mymr
    1429, 120,  // ior -> Ethi
    1433, 515,  // iru -> Taml
    1437, 10,  // isk -> Arab
    1441, 180,  // itk -> Hebr
    1445, 100,  // itl -> Cyrl
    1449, 65,  // iu -> Cans
    1452, 180,  // iw -> Hebr
    1455, 205,  // ja -> Jpan
    1458, 10,  // jad -> Arab
    1462, 10,  // jat -> Arab
    1466, 180,  // jbe -> Hebr
    1470, 10,  // jbn -> Arab
    1474, 100,  // jct -> Cyrl
    1478, 550,  // jda -> Tibt
    1482, 10,  // jdg -> Arab
    1486, 100,  // jdt -> Cyrl
    1490, 105,  // jee -> Deva
    1494, 125,  // jge -> Geor
    1498, 180,  // ji -> Hebr
    1501, 160,  // jje -> Hang
    1505, 350,  // jkp -> Mymr
    1509, 105,  // jml -> Deva
    1513, 500,  // jna -> Takr
    1517, 10,  // jnd -> Arab
    1521, 105,  // jnl -> Deva
    1525, 105,  // jns -> Deva
    1529, 10,  // jog -> Arab
    1533, 180,  // jpa -> Hebr
    1537, 180,  // jpr -> Hebr
    1541, 180,  // jrb -> Hebr
    1545, 210,  // juc -> Jurc
    1549, 105,  // jul -> Deva
    1553, 385,  // jun -> Orya
    1557, 385,  // juy -> Orya
    1561, 550,  // jya -> Tibt
    1565, 180,  // jye -> Hebr
    1569, 125,  // ka -> Geor
    1572, 100,  // kaa -> Cyrl
    1576, 100,  // kap -> Cyrl
    1580, 30,  // kaw -> Bali
    1584, 100,  // kbd -> Cyrl
    1588, 550,  // kbg -> Tibt
    1592, 10,  // kbu -> Arab
    1596, 10,  // kby -> Arab
    1600, 100,  // kca -> Cyrl
    1604, 10,  // kcy -> Arab
    1608, 45,  // kdq -> Beng
    1612, 545,  // kdt -> Thai
    1616, 100,  // ket -> Cyrl
    1620, 325,  // kev -> Mlym
    1624, 105,  // kex -> Deva
    1628, 530,  // key -> Telu
    1632, 240,  // kfa -> Knda
    1636, 105,  // kfb -> Deva
    1640, 530,  // kfc -> Telu
    1644, 240,  // kfd -> Knda
    1648, 515,  // kfe -> Taml
    1652, 240,  // kfg -> Knda
    1656, 325,  // kfh -> Mlym
    1660, 515,  // kfi -> Taml
    1664, 105,  // kfk -> Deva
    1668, 10,  // kfm -> Arab
    1672, 105,  // kfp -> Deva
    1676, 105,  // kfq -> Deva
    1680, 105,  // kfr -> Deva
    1684, 105,  // kfs -> Deva
    1688, 105,  // kfu -> Deva
    1692, 105,  // kfx -> Deva
    1696, 105,  // kfy -> Deva
    1700, 105,  // kgj -> Deva
    1704, 550,  // kgy -> Tibt
    1708, 510,  // khb -> Talu
    1712, 545,  // khf -> Thai
    1716, 550,  // khg -> Tibt
    1720, 105,  // khn -> Deva
    1724, 55,  // kho -> Brah
    1728, 350,  // kht -> Mymr
    1732, 100,  // khv -> Cyrl
    1736, 10,  // khw -> Arab
    1740, 105,  // kif -> Deva
    1744, 100,  // kim -> Cyrl
    1748, 105,  // kip -> Deva
    1752, 255,  // kjg -> Laoo
    1756, 100,  // kjh -> Cyrl
    1760, 105,  // kjl -> Deva
    1764, 105,  // kjo -> Deva
    1768, 350,  // kjp -> Mymr
    1772, 545,  // kjt -> Thai
    1776, 550,  // kjz -> Tibt
    1780, 100,  // kk -> Cyrl
    1783, 10,  // kk_AF -> Arab
    1789, 10,  // kk_CN -> Arab
    1795, 10,  // kk_IR -> Arab
    1801, 10,  // kk_MN -> Arab
    1807, 550,  // kkf -> Tibt
    1811, 250,  // kkh -> Lana
    1815, 105,  // kkt -> Deva
    1819, 105,  // kle -> Deva
    1823, 10,  // klj -> Arab
    1827, 105,  // klr -> Deva
    1831, 230,  // km -> Khmr
    1834, 105,  // kmj -> Deva
    1838, 10,  // kmz -> Arab
    1842, 240,  // kn -> Knda
    1845, 105,  // knn -> Deva
    1849, 245,  // ko -> Kore
    1852, 100,  // koi -> Cyrl
    1856, 105,  // kok -> Deva
    1860, 100,  // kpt -> Cyrl
    1864, 100,  // kpy -> Cyrl
    1868, 490,  // kqd -> Syrc
    1872, 120,  // kqy -> Ethi
    1876, 105,  // kra -> Deva
    1880, 100,  // krc -> Cyrl
    1884, 100,  // krk -> Cyrl
    1888, 230,  // krr -> Khmr
    1892, 105,  // kru -> Deva
    1896, 230,  // krv -> Khmr
    1900, 10,  // ks -> Arab
    1903, 350,  // ksu -> Mymr
    1907, 350,  // ksw -> Mymr
    1911, 105,  // ksz -> Deva
    1915, 120,  // ktb -> Ethi
    1919, 105,  // kte -> Deva
    1923, 10,  // ktl -> Arab
    1927, 415,  // ktp -> Plrd
    1931, 100,  // ku_AM -> Cyrl
    1937, 100,  // ku_AZ -> Cyrl
    1943, 100,  // ku_GE -> Cyrl
    1949, 10,  // ku_IQ -> Arab
    1955, 10,  // ku_IR -> Arab
    1961, 10,  // ku_LB -> Arab
    1967, 100,  // ku_TM -> Cyrl
    1973, 255,  // kuf -> Laoo
    1977, 100,  // kum -> Cyrl
    1981, 100,  // kv -> Cyrl
    1984, 100,  // kva -> Cyrl
    1988, 350,  // kvq -> Mymr
    1992, 350,  // kvt -> Mymr
    1996, 10,  // kvx -> Arab
    2000, 215,  // kvy -> Kali
    2004, 105,  // kwx -> Deva
    2008, 350,  // kxf -> Mymr
    2012, 350,  // kxk -> Mymr
    2016, 545,  // kxm -> Thai
    2020, 10,  // kxp -> Arab
    2024, 100,  // ky -> Cyrl
    2027, 10,  // ky_CN -> Arab
    2033, 215,  // kyu -> Kali
    2037, 105,  // kyv -> Deva
    2041, 105,  // kyw -> Deva
    2045, 105,  // kzq -> Deva
    2049, 275,  // lab -> Lina
    2053, 180,  // lad -> Hebr
    2057, 105,  // lae -> Deva
    2061, 10,  // lah -> Arab
    2065, 100,  // lbe -> Cyrl
    2069, 105,  // lbf -> Deva
    2073, 550,  // lbj -> Tibt
    2077, 105,  // lbm -> Deva
    2081, 255,  // lbo -> Laoo
    2085, 105,  // lbr -> Deva
    2089, 545,  // lcp -> Thai
    2093, 270,  // lep -> Lepc
    2097, 100,  // lez -> Cyrl
    2101, 105,  // lhm -> Deva
    2105, 490,  // lhs -> Syrc
    2109, 105,  // lif -> Deva
    2113, 285,  // lis -> Lisu
    2117, 550,  // lkh -> Tibt
    2121, 10,  // lki -> Arab
    2125, 105,  // lmh -> Deva
    2129, 530,  // lmn -> Telu
    2133, 255,  // lo -> Laoo
    2136, 105,  // loy -> Deva
    2140, 415,  // lpo -> Plrd
    2144, 10,  // lrc -> Arab
    2148, 10,  // lrk -> Arab
    2152, 10,  // lrl -> Arab
    2156, 10,  // lsa -> Arab
    2160, 180,  // lsd -> Hebr
    2164, 10,  // lss -> Arab
    2168, 175,  // ltc -> Hant
    2172, 170,  // luh -> Hans
    2176, 550,  // luk -> Tibt
    2180, 105,  // luu -> Deva
    2184, 10,  // luv -> Arab
    2188, 10,  // luz -> Arab
    2192, 545,  // lwl -> Thai
    2196, 545,  // lwm -> Thai
    2200, 550,  // lya -> Tibt
    2204, 175,  // lzh -> Hant
    2208, 125,  // lzz_GE -> Geor
    2215, 105,  // mag -> Deva
    2219, 105,  // mai -> Deva
    2223, 10,  // mby -> Arab
    2227, 10,  // mde -> Arab
    2231, 100,  // mdf -> Cyrl
    2235, 120,  // mdx -> Ethi
    2239, 120,  // mdy -> Ethi
    2243, 10,  // mey -> Arab
    2247, 10,  // mfa -> Arab
    2251, 10,  // mfi -> Arab
    2255, 265,  // mga -> Latg
    2259, 105,  // mgp -> Deva
    2263, 10,  // mhj -> Arab
    2267, 300,  // mid -> Mand
    2271, 105,  // mjl -> Deva
    2275, 325,  // mjq -> Mlym
    2279, 325,  // mjr -> Mlym
    2283, 105,  // mjt -> Deva
    2287, 530,  // mju -> Telu
    2291, 325,  // mjv -> Mlym
    2295, 105,  // mjz -> Deva
    2299, 100,  // mk -> Cyrl
    2302, 105,  // mkb -> Deva
    2306, 105,  // mke -> Deva
    2310, 10,  // mki -> Arab
    2314, 545,  // mkm -> Thai
    2318, 325,  // ml -> Mlym
    2321, 545,  // mlf -> Thai
    2325, 100,  // mn -> Cyrl
    2328, 335,  // mn_CN -> Mong
    2334, 335,  // mnc -> Mong
    2338, 45,  // mni -> Beng
    2342, 10,  // mnj -> Arab
    2346, 170,  // mnp -> Hans
    2350, 100,  // mns -> Cyrl
    2354, 350,  // mnw -> Mymr
    2358, 545,  // mpz -> Thai
    2362, 105,  // mr -> Deva
    2365, 545,  // mra -> Thai
    2369, 100,  // mrj -> Cyrl
    2373, 340,  // mro -> Mroo
    2377, 105,  // mrr -> Deva
    2381, 10,  // ms_CC -> Arab
    2387, 100,  // mtm -> Cyrl
    2391, 105,  // mtr -> Deva
    2395, 100,  // mud -> Cyrl
    2399, 550,  // muk -> Tibt
    2403, 105,  // mut -> Deva
    2407, 515,  // muv -> Taml
    2411, 120,  // muz -> Ethi
    2415, 10,  // mve -> Arab
    2419, 335,  // mvf -> Mong
    2423, 10,  // mvy -> Arab
    2427, 120,  // mvz -> Ethi
    2431, 105,  // mwr -> Deva
    2435, 350,  // mwt -> Mymr
    2439, 190,  // mww -> Hmnp
    2443, 350,  // my -> Mymr
    2446, 120,  // mym -> Ethi
    2450, 100,  // myv -> Cyrl
    2454, 300,  // myz -> Mand
    2458, 10,  // mzb -> Arab
    2462, 10,  // mzn -> Arab
    2466, 170,  // nan -> Hans
    2470, 175,  // nan_MO -> Hant
    2477, 175,  // nan_TW -> Hant
    2484, 105,  // nao -> Deva
    2488, 105,  // ncd -> Deva
    2492, 255,  // ncq -> Laoo
    2496, 100,  // ndf -> Cyrl
    2500, 105,  // ne -> Deva
    2503, 100,  // neg -> Cyrl
    2507, 550,  // neh -> Tibt
    2511, 585,  // nei -> Xsux
    2515, 255,  // nev -> Laoo
    2519, 105,  // new -> Deva
    2523, 255,  // ngt -> Laoo
    2527, 100,  // nio -> Cyrl
    2531, 530,  // nit -> Telu
    2535, 100,  // niv -> Cyrl
    2539, 10,  // nli -> Arab
    2543, 105,  // nll -> Deva
    2547, 10,  // nlm -> Arab
    2551, 105,  // nlx -> Deva
    2555, 105,  // nmm -> Deva
    2559, 575,  // nnp -> Wcho
    2563, 250,  // nod -> Lana
    2567, 105,  // noe -> Deva
    2571, 100,  // nog -> Cyrl
    2575, 105,  // noi -> Deva
    2579, 435,  // non -> Runr
    2583, 590,  // nos -> Yiii
    2587, 550,  // npb -> Tibt
    2591, 365,  // nqo -> Nkoo
    2595, 435,  // nrn -> Runr
    2599, 590,  // nsd -> Yiii
    2603, 590,  // nsf -> Yiii
    2607, 65,  // nsk -> Cans
    2611, 555,  // nst -> Tnsa
    2615, 590,  // nsv -> Yiii
    2619, 590,  // nty -> Yiii
    2623, 10,  // ntz -> Arab
    2627, 360,  // nwc -> Newa
    2631, 105,  // nwx -> Deva
    2635, 545,  // nyl -> Thai
    2639, 10,  // nyq -> Arab
    2643, 545,  // nyw -> Thai
    2647, 100,  // oaa -> Cyrl
    2651, 100,  // oac -> Cyrl
    2655, 45,  // oak -> Beng
    2659, 490,  // oar -> Syrc
    2663, 125,  // oav -> Geor
    2667, 410,  // obm -> Phnx
    2671, 350,  // obr -> Mymr
    2675, 455,  // och -> Seal
    2679, 10,  // odk -> Arab
    2683, 585,  // oht -> Xsux
    2687, 65,  // oj -> Cans
    2690, 65,  // ojs -> Cans
    2694, 160,  // okm -> Hang
    2698, 165,  // oko -> Hani
    2702, 230,  // okz -> Khmr
    2706, 105,  // ola -> Deva
    2710, 550,  // ole -> Tibt
    2714, 100,  // omk -> Cyrl
    2718, 345,  // omp -> Mtei
    2722, 330,  // omr -> Modi
    2726, 350,  // omx -> Mymr
    2730, 10,  // omy -> Arab
    2734, 105,  // oon -> Deva
    2738, 385,  // or -> Orya
    2741, 530,  // ort -> Telu
    2745, 10,  // oru -> Arab
    2749, 100,  // orv -> Cyrl
    2753, 100,  // os -> Cyrl
    2756, 390,  // osa -> Osge
    2760, 195,  // osc -> Ital
    2764, 100,  // osd -> Cyrl
    2768, 200,  // osi -> Java
    2772, 10,  // ota -> Arab
    2776, 550,  // otb -> Tibt
    2780, 380,  // otk -> Orkh
    2784, 140,  // oty -> Gran
    2788, 395,  // oui -> Ougr
    2792, 255,  // oyb -> Laoo
    2796, 155,  // pa -> Guru
    2799, 10,  // pa_PK -> Arab
    2805, 405,  // pal -> Phli
    2809, 100,  // paq -> Cyrl
    2813, 10,  // pbt -> Arab
    2817, 230,  // pcb -> Khmr
    2821, 350,  // pce -> Mymr
    2825, 325,  // pcf -> Mlym
    2829, 325,  // pcg -> Mlym
    2833, 105,  // pch -> Deva
    2837, 105,  // pci -> Deva
    2841, 530,  // pcj -> Telu
    2845, 385,  // peg -> Orya
    2849, 580,  // peo -> Xpeo
    2853, 225,  // pgd -> Khar
    2857, 105,  // pgg -> Deva
    2861, 370,  // pgl -> Ogam
    2865, 195,  // pgn -> Ital
    2869, 105,  // phd -> Deva
    2873, 350,  // phk -> Mymr
    2877, 10,  // phl -> Arab
    2881, 410,  // phn -> Phnx
    2885, 255,  // pho -> Laoo
    2889, 10,  // phr -> Arab
    2893, 545,  // pht -> Thai
    2897, 545,  // phu -> Thai
    2901, 10,  // phv -> Arab
    2905, 105,  // phw -> Deva
    2909, 105,  // pi_IN -> Deva
    2915, 470,  // pi_LK -> Sinh
    2921, 350,  // pi_MM -> Mymr
    2927, 545,  // pi_TH -> Thai
    2933, 55,  // pka -> Brah
    2937, 325,  // pkr -> Mlym
    2941, 10,  // plk -> Arab
    2945, 350,  // pll -> Mymr
    2949, 55,  // pmh -> Brah
    2953, 145,  // pnt -> Grek
    2957, 100,  // pnt_RU -> Cyrl
    2964, 255,  // pnx -> Laoo
    2968, 10,  // prc -> Arab
    2972, 10,  // prd -> Arab
    2976, 545,  // prt -> Thai
    2980, 10,  // prx -> Arab
    2984, 10,  // ps -> Arab
    2987, 10,  // psh -> Arab
    2991, 10,  // psi -> Arab
    2995, 10,  // pst -> Arab
    2999, 55,  // psu -> Brah
    3003, 105,  // pum -> Deva
    3007, 350,  // pwo -> Mymr
    3011, 105,  // pwr -> Deva
    3015, 545,  // pww -> Thai
    3019, 350,  // pyx -> Mymr
    3023, 10,  // qxq -> Arab
    3027, 105,  // raa -> Deva
    3031, 105,  // rab -> Deva
    3035, 105,  // raf -> Deva
    3039, 45,  // rah -> Beng
    3043, 105,  // raj -> Deva
    3047, 105,  // rav -> Deva
    3051, 350,  // rbb -> Mymr
    3055, 10,  // rdb -> Arab
    3059, 385,  // rei -> Orya
    3063, 430,  // rhg -> Rohg
    3067, 105,  // rji -> Deva
    3071, 105,  // rjs -> Deva
    3075, 230,  // rka -> Khmr
    3079, 350,  // rki -> Mymr
    3083, 45,  // rkt -> Beng
    3087, 20,  // rmi -> Armn
    3091, 10,  // rmt -> Arab
    3095, 350,  // rmz -> Mymr
    3099, 100,  // rsk -> Cyrl
    3103, 105,  // rtw -> Deva
    3107, 100,  // ru -> Cyrl
    3110, 100,  // rue -> Cyrl
    3114, 100,  // rut -> Cyrl
    3118, 105,  // rwr -> Deva
    3122, 220,  // ryu -> Kana
    3126, 105,  // sa -> Deva
    3129, 100,  // sah -> Cyrl
    3133, 440,  // sam -> Samr
    3137, 375,  // sat -> Olck
    3141, 450,  // saz -> Saur
    3145, 10,  // sbn -> Arab
    3149, 550,  // sbu -> Tibt
    3153, 105,  // sck -> Deva
    3157, 10,  // scl -> Arab
    3161, 105,  // scp -> Deva
    3165, 255,  // sct -> Laoo
    3169, 500,  // scu -> Takr
    3173, 145,  // scx -> Grek
    3177, 10,  // sd -> Arab
    3180, 105,  // sd_IN -> Deva
    3186, 10,  // sdb -> Arab
    3190, 10,  // sdf -> Arab
    3194, 10,  // sdg -> Arab
    3198, 10,  // sdh -> Arab
    3202, 45,  // sdr -> Beng
    3206, 10,  // sds -> Arab
    3210, 100,  // sel -> Cyrl
    3214, 415,  // sfm -> Plrd
    3218, 100,  // sgh -> Cyrl
    3222, 105,  // sgj -> Deva
    3226, 10,  // sgr -> Arab
    3230, 550,  // sgt -> Tibt
    3234, 120,  // sgw -> Ethi
    3238, 10,  // sgy -> Arab
    3242, 10,  // shd -> Arab
    3246, 535,  // shi -> Tfng
    3250, 10,  // shm -> Arab
    3254, 350,  // shn -> Mymr
    3258, 10,  // shu -> Arab
    3262, 10,  // shv -> Arab
    3266, 470,  // si -> Sinh
    3269, 100,  // sia -> Cyrl
    3273, 550,  // sip -> Tibt
    3277, 10,  // siy -> Arab
    3281, 10,  // siz -> Arab
    3285, 170,  // sjc -> Hans
    3289, 100,  // sjd -> Cyrl
    3293, 105,  // sjp -> Deva
    3297, 100,  // sjt -> Cyrl
    3301, 545,  // skb -> Thai
    3305, 105,  // skj -> Deva
    3309, 10,  // skr -> Arab
    3313, 240,  // sle -> Knda
    3317, 590,  // smh -> Yiii
    3321, 440,  // smp -> Samr
    3325, 230,  // smu -> Khmr
    3329, 10,  // smy -> Arab
    3333, 525,  // soa -> Tavt
    3337, 475,  // sog -> Sogd
    3341, 105,  // soi -> Deva
    3345, 545,  // sou -> Thai
    3349, 550,  // spt -> Tibt
    3353, 385,  // spv -> Orya
    3357, 10,  // sqo -> Arab
    3361, 255,  // sqq -> Laoo
    3365, 10,  // sqt -> Arab
    3369, 100,  // sr -> Cyrl
    3372, 480,  // srb -> Sora
    3376, 10,  // srh -> Arab
    3380, 105,  // srx -> Deva
    3384, 10,  // srz -> Arab
    3388, 10,  // ssh -> Arab
    3392, 255,  // sss -> Laoo
    3396, 10,  // sts -> Arab
    3400, 250,  // stu -> Lana
    3404, 505,  // stu_CN -> Tale
    3411, 120,  // stv -> Ethi
    3415, 100,  // sty -> Cyrl
    3419, 105,  // suz -> Deva
    3423, 125,  // sva -> Geor
    3427, 10,  // swb -> Arab
    3431, 165,  // swi -> Hani
    3435, 105,  // swv -> Deva
    3439, 435,  // sxu -> Runr
    3443, 490,  // syc -> Syrc
    3447, 45,  // syl -> Beng
    3451, 490,  // syn -> Syrc
    3455, 490,  // syr -> Syrc
    3459, 105,  // syw -> Deva
    3463, 515,  // ta -> Taml
    3466, 100,  // tab -> Cyrl
    3470, 105,  // taj -> Deva
    3474, 495,  // tbk -> Tagb
    3478, 105,  // tcn -> Deva
    3482, 350,  // tco -> Mymr
    3486, 515,  // tcx -> Taml
    3490, 240,  // tcy -> Knda
    3494, 535,  // tda -> Tfng
    3498, 105,  // tdb -> Deva
    3502, 505,  // tdd -> Tale
    3506, 105,  // tdg -> Deva
    3510, 105,  // tdh -> Deva
    3514, 530,  // te -> Telu
    3517, 200,  // tes -> Java
    3521, 100,  // tg -> Cyrl
    3524, 10,  // tg_PK -> Arab
    3530, 105,  // tge -> Deva
    3534, 550,  // tgf -> Tibt
    3538, 545,  // th -> Thai
    3541, 105,  // the -> Deva
    3545, 105,  // thf -> Deva
    3549, 505,  // thi -> Tale
    3553, 105,  // thl -> Deva
    3557, 545,  // thm -> Thai
    3561, 105,  // thq -> Deva
    3565, 105,  // thr -> Deva
    3569, 105,  // ths -> Deva
    3573, 120,  // ti -> Ethi
    3576, 120,  // tig -> Ethi
    3580, 105,  // tij -> Deva
    3584, 100,  // tin -> Cyrl
    3588, 350,  // tjl -> Mymr
    3592, 10,  // tjo -> Arab
    3596, 105,  // tkb -> Deva
    3600, 10,  // tks -> Arab
    3604, 105,  // tkt -> Deva
    3608, 490,  // tmr -> Syrc
    3612, 60,  // tnv -> Cakm
    3616, 10,  // tov -> Arab
    3620, 230,  // tpu -> Khmr
    3624, 10,  // tra -> Arab
    3628, 180,  // trg -> Hebr
    3632, 10,  // trm -> Arab
    3636, 10,  // trw -> Arab
    3640, 145,  // tsd -> Grek
    3644, 550,  // tsj -> Tibt
    3648, 100,  // tt -> Cyrl
    3651, 255,  // tth -> Laoo
    3655, 255,  // tto -> Laoo
    3659, 545,  // tts -> Thai
    3663, 105,  // ttz -> Deva
    3667, 350,  // tvn -> Mymr
    3671, 550,  // twm -> Tibt
    3675, 520,  // txg -> Tang
    3679, 560,  // txo -> Toto
    3683, 525,  // tyr -> Tavt
    3687, 100,  // tyv -> Cyrl
    3691, 100,  // ude -> Cyrl
    3695, 325,  // udg -> Mlym
    3699, 100,  // udi -> Cyrl
    3703, 100,  // udm -> Cyrl
    3707, 10,  // ug -> Arab
    3710, 100,  // ug_KZ -> Cyrl
    3716, 100,  // ug_MN -> Cyrl
    3722, 565,  // uga -> Ugar
    3726, 100,  // ugh -> Cyrl
    3730, 545,  // ugo -> Thai
    3734, 100,  // uk -> Cyrl
    3737, 385,  // uki -> Orya
    3741, 100,  // ulc -> Cyrl
    3745, 45,  // unr -> Beng
    3749, 105,  // unr_NP -> Deva
    3756, 45,  // unx -> Beng
    3760, 10,  // ur -> Arab
    3763, 545,  // urk -> Thai
    3767, 10,  // ush -> Arab
    3771, 145,  // uum -> Grek
    3775, 10,  // uz_AF -> Arab
    3781, 100,  // uz_CN -> Cyrl
    3787, 10,  // uzs -> Arab
    3791, 515,  // vaa -> Taml
    3795, 10,  // vaf -> Arab
    3799, 105,  // vah -> Deva
    3803, 570,  // vai -> Vaii
    3807, 105,  // vas -> Deva
    3811, 105,  // vav -> Deva
    3815, 105,  // vay -> Deva
    3819, 10,  // vgr -> Arab
    3823, 105,  // vjk -> Deva
    3827, 240,  // vmd -> Knda
    3831, 10,  // vmh -> Arab
    3835, 120,  // wal -> Ethi
    3839, 10,  // wbk -> Arab
    3843, 530,  // wbq -> Telu
    3847, 105,  // wbr -> Deva
    3851, 120,  // wle -> Ethi
    3855, 105,  // wly -> Deva
    3859, 105,  // wme -> Deva
    3863, 10,  // wne -> Arab
    3867, 10,  // wni -> Arab
    3871, 530,  // wsg -> Telu
    3875, 10,  // wsv -> Arab
    3879, 105,  // wtm -> Deva
    3883, 170,  // wuu -> Hans
    3887, 0,  // xag -> Aghb
    3891, 100,  // xal -> Cyrl
    3895, 120,  // xan -> Ethi
    3899, 100,  // xas -> Cyrl
    3903, 85,  // xco -> Chrs
    3907, 70,  // xcr -> Cari
    3911, 100,  // xdq -> Cyrl
    3915, 10,  // xhe -> Arab
    3919, 230,  // xhm -> Khmr
    3923, 385,  // xis -> Orya
    3927, 10,  // xka -> Arab
    3931, 10,  // xkc -> Arab
    3935, 550,  // xkf -> Tibt
    3939, 10,  // xkj -> Arab
    3943, 230,  // xkk -> Khmr
    3947, 10,  // xkp -> Arab
    3951, 290,  // xlc -> Lyci
    3955, 295,  // xld -> Lydi
    3959, 115,  // xly -> Elym
    3963, 125,  // xmf -> Geor
    3967, 305,  // xmn -> Mani
    3971, 320,  // xmr -> Merc
    3975, 355,  // xna -> Narb
    3979, 105,  // xnr -> Deva
    3983, 145,  // xpg -> Grek
    3987, 370,  // xpi -> Ogam
    3991, 100,  // xpm -> Cyrl
    3995, 420,  // xpr -> Prti
    3999, 100,  // xrm -> Cyrl
    4003, 100,  // xrn -> Cyrl
    4007, 445,  // xsa -> Sarb
    4011, 465,  // xsd -> Sidt
    4015, 105,  // xsr -> Deva
    4019, 55,  // xtq -> Brah
    4023, 515,  // xua -> Taml
    4027, 515,  // xub -> Taml
    4031, 515,  // xuj -> Taml
    4035, 195,  // xve -> Ital
    4039, 10,  // xvi -> Arab
    4043, 100,  // xwo -> Cyrl
    4047, 310,  // xzh -> Marc
    4051, 100,  // yai -> Cyrl
    4055, 105,  // ybh -> Deva
    4059, 105,  // ybi -> Deva
    4063, 10,  // ydg -> Arab
    4067, 325,  // yea -> Mlym
    4071, 145,  // yej -> Grek
    4075, 530,  // yeu -> Telu
    4079, 415,  // ygp -> Plrd
    4083, 180,  // yhd -> Hebr
    4087, 180,  // yi -> Hebr
    4090, 590,  // yig -> Yiii
    4094, 180,  // yih -> Hebr
    4098, 350,  // yin -> Mymr
    4102, 590,  // yiv -> Yiii
    4106, 100,  // ykg -> Cyrl
    4110, 100,  // ykh -> Cyrl
    4114, 415,  // yna -> Plrd
    4118, 100,  // ynk -> Cyrl
    4122, 205,  // yoi -> Jpan
    4126, 545,  // yoy -> Thai
    4130, 100,  // yrk -> Cyrl
    4134, 590,  // ysd -> Yiii
    4138, 590,  // ysn -> Yiii
    4142, 590,  // ysp -> Yiii
    4146, 100,  // ysr -> Cyrl
    4150, 415,  // ysy -> Plrd
    4154, 180,  // yud -> Hebr
    4158, 175,  // yue -> Hant
    4162, 170,  // yue_CN -> Hans
    4169, 100,  // yug -> Cyrl
    4173, 100,  // yux -> Cyrl
    4177, 415,  // ywq -> Plrd
    4181, 415,  // ywu -> Plrd
    4185, 550,  // zau -> Tibt
    4189, 10,  // zba -> Arab
    4193, 165,  // zch -> Hani
    4197, 10,  // zdj -> Arab
    4201, 165,  // zeh -> Hani
    4205, 535,  // zen -> Tfng
    4209, 165,  // zgb -> Hani
    4213, 535,  // zgh -> Tfng
    4217, 165,  // zgm -> Hani
    4221, 165,  // zgn -> Hani
    4225, 170,  // zh -> Hans
    4228, 175,  // zh_AU -> Hant
    4234, 175,  // zh_BN -> Hant
    4240, 175,  // zh_GB -> Hant
    4246, 175,  // zh_GF -> Hant
    4252, 175,  // zh_HK -> Hant
    4258, 175,  // zh_ID -> Hant
    4264, 175,  // zh_MO -> Hant
    4270, 175,  // zh_PA -> Hant
    4276, 175,  // zh_PF -> Hant
    4282, 175,  // zh_PH -> Hant
    4288, 175,  // zh_SR -> Hant
    4294, 175,  // zh_TH -> Hant
    4300, 175,  // zh_TW -> Hant
    4306, 175,  // zh_US -> Hant
    4312, 175,  // zh_VN -> Hant
    4318, 165,  // zhd -> Hani
    4322, 350,  // zkn -> Mymr
    4326, 100,  // zko -> Cyrl
    4330, 235,  // zkt -> Kits
    4334, 100,  // zkz -> Cyrl
    4338, 165,  // zlj -> Hani
    4342, 165,  // zln -> Hani
    4346, 165,  // zlq -> Hani
    4350, 165,  // zqe -> Hani
    4354, 385,  // zrg -> Orya
    4358, 180,  // zrp -> Hebr
    4362, 10,  // zum -> Arab
    4366, 120,  // zwa -> Ethi
    4370, 165,  // zyg -> Hani
    4374, 165,  // zyn -> Hani
    4378, 165,  // zzj -> Hani
};

// ======================================================================
// Parent locale table
const char parentLocaleChars[] =
    "az_Arab\0az_Cyrl\0bal_Latn\0blt_Latn\0bm_Nkoo\0bs_Cyrl\0byn_Latn\0"
    "cu_Glag\0dje_Arab\0dyo_Arab\0en_001\0en_150\0en_AG\0en_AI\0en_AT\0"
    "en_AU\0en_BB\0en_BE\0en_BM\0en_BS\0en_BW\0en_BZ\0en_CC\0en_CH\0"
    "en_CK\0en_CM\0en_CX\0en_CY\0en_CZ\0en_DE\0en_DG\0en_DK\0en_DM\0"
    "en_Dsrt\0en_EE\0en_ER\0en_ES\0en_FI\0en_FJ\0en_FK\0en_FM\0en_FR\0"
    "en_GB\0en_GD\0en_GE\0en_GG\0en_GH\0en_GI\0en_GM\0en_GS\0en_GY\0"
    "en_HK\0en_HU\0en_ID\0en_IE\0en_IL\0en_IM\0en_IN\0en_IO\0en_IT\0"
    "en_JE\0en_JM\0en_KE\0en_KI\0en_KN\0en_KY\0en_LC\0en_LR\0en_LS\0"
    "en_LT\0en_LV\0en_MG\0en_MO\0en_MS\0en_MT\0en_MU\0en_MV\0en_MW\0"
    "en_MY\0en_NA\0en_NF\0en_NG\0en_NL\0en_NO\0en_NR\0en_NU\0en_NZ\0"
    "en_PG\0en_PK\0en_PL\0en_PN\0en_PT\0en_PW\0en_RO\0en_RW\0en_SB\0"
    "en_SC\0en_SD\0en_SE\0en_SG\0en_SH\0en_SI\0en_SK\0en_SL\0en_SS\0"
    "en_SX\0en_SZ\0en_Shaw\0en_TC\0en_TK\0en_TO\0en_TT\0en_TV\0en_TZ\0"
    "en_UA\0en_UG\0en_VC\0en_VG\0en_VU\0en_WS\0en_ZA\0en_ZM\0en_ZW\0"
    "es_419\0es_AR\0es_BO\0es_BR\0es_BZ\0es_CL\0es_CO\0es_CR\0es_CU\0"
    "es_DO\0es_EC\0es_GT\0es_HN\0es_JP\0es_MX\0es_NI\0es_PA\0es_PE\0"
    "es_PR\0es_PY\0es_SV\0es_US\0es_UY\0es_VE\0ff_Adlm\0ff_Arab\0ha_Arab\0"
    "hi_Latn\0iu_Latn\0kaa_Latn\0kk_Arab\0kok_Latn\0ks_Deva\0ku_Arab\0"
    "kxv_Deva\0kxv_Orya\0kxv_Telu\0ky_Arab\0ky_Latn\0ml_Arab\0mn_Mong\0"
    "mni_Mtei\0ms_Arab\0nb\0nn\0no\0no_NO\0pa_Arab\0pt_AO\0pt_CH\0"
    "pt_CV\0pt_FR\0pt_GQ\0pt_GW\0pt_LU\0pt_MO\0pt_MZ\0pt_PT\0pt_ST\0"
    "pt_TL\0root\0sat_Deva\0sd_Deva\0sd_Khoj\0sd_Sind\0shi_Latn\0so_Arab\0"
    "sr_Latn\0suz_Sunu\0sw_Arab\0tg_Arab\0ug_Cyrl\0uz_Arab\0uz_Cyrl\0"
    "vai_Latn\0wo_Arab\0yo_Arab\0yue_Hans\0zh_Hant\0zh_Hant_HK\0zh_Hant_MO\0"
    "";

const int32_t parentLocaleTable[] = {
    0, 1167,  // az_Arab -> root
    8, 1167,  // az_Cyrl -> root
    16, 1167,  // bal_Latn -> root
    25, 1167,  // blt_Latn -> root
    34, 1167,  // bm_Nkoo -> root
    42, 1167,  // bs_Cyrl -> root
    50, 1167,  // byn_Latn -> root
    59, 1167,  // cu_Glag -> root
    67, 1167,  // dje_Arab -> root
    76, 1167,  // dyo_Arab -> root
    92, 85,  // en_150 -> en_001
    99, 85,  // en_AG -> en_001
    105, 85,  // en_AI -> en_001
    111, 92,  // en_AT -> en_150
    117, 85,  // en_AU -> en_001
    123, 85,  // en_BB -> en_001
    129, 92,  // en_BE -> en_150
    135, 85,  // en_BM -> en_001
    141, 85,  // en_BS -> en_001
    147, 85,  // en_BW -> en_001
    153, 85,  // en_BZ -> en_001
    159, 85,  // en_CC -> en_001
    165, 92,  // en_CH -> en_150
    171, 85,  // en_CK -> en_001
    177, 85,  // en_CM -> en_001
    183, 85,  // en_CX -> en_001
    189, 85,  // en_CY -> en_001
    195, 92,  // en_CZ -> en_150
    201, 92,  // en_DE -> en_150
    207, 85,  // en_DG -> en_001
    213, 92,  // en_DK -> en_150
    219, 85,  // en_DM -> en_001
    225, 1167,  // en_Dsrt -> root
    233, 92,  // en_EE -> en_150
    239, 85,  // en_ER -> en_001
    245, 92,  // en_ES -> en_150
    251, 92,  // en_FI -> en_150
    257, 85,  // en_FJ -> en_001
    263, 85,  // en_FK -> en_001
    269, 85,  // en_FM -> en_001
    275, 92,  // en_FR -> en_150
    281, 85,  // en_GB -> en_001
    287, 85,  // en_GD -> en_001
    293, 92,  // en_GE -> en_150
    299, 85,  // en_GG -> en_001
    305, 85,  // en_GH -> en_001
    311, 85,  // en_GI -> en_001
    317, 85,  // en_GM -> en_001
    323, 85,  // en_GS -> en_001
    329, 85,  // en_GY -> en_001
    335, 85,  // en_HK -> en_001
    341, 92,  // en_HU -> en_150
    347, 85,  // en_ID -> en_001
    353, 85,  // en_IE -> en_001
    359, 85,  // en_IL -> en_001
    365, 85,  // en_IM -> en_001
    371, 85,  // en_IN -> en_001
    377, 85,  // en_IO -> en_001
    383, 92,  // en_IT -> en_150
    389, 85,  // en_JE -> en_001
    395, 85,  // en_JM -> en_001
    401, 85,  // en_KE -> en_001
    407, 85,  // en_KI -> en_001
    413, 85,  // en_KN -> en_001
    419, 85,  // en_KY -> en_001
    425, 85,  // en_LC -> en_001
    431, 85,  // en_LR -> en_001
    437, 85,  // en_LS -> en_001
    443, 92,  // en_LT -> en_150
    449, 92,  // en_LV -> en_150
    455, 85,  // en_MG -> en_001
    461, 85,  // en_MO -> en_001
    467, 85,  // en_MS -> en_001
    473, 85,  // en_MT -> en_001
    479, 85,  // en_MU -> en_001
    485, 85,  // en_MV -> en_001
    491, 85,  // en_MW -> en_001
    497, 85,  // en_MY -> en_001
    503, 85,  // en_NA -> en_001
    509, 85,  // en_NF -> en_001
    515, 85,  // en_NG -> en_001
    521, 92,  // en_NL -> en_150
    527, 92,  // en_NO -> en_150
    533, 85,  // en_NR -> en_001
    539, 85,  // en_NU -> en_001
    545, 85,  // en_NZ -> en_001
    551, 85,  // en_PG -> en_001
    557, 85,  // en_PK -> en_001
    563, 92,  // en_PL -> en_150
    569, 85,  // en_PN -> en_001
    575, 92,  // en_PT -> en_150
    581, 85,  // en_PW -> en_001
    587, 92,  // en_RO -> en_150
    593, 85,  // en_RW -> en_001
    599, 85,  // en_SB -> en_001
    605, 85,  // en_SC -> en_001
    611, 85,  // en_SD -> en_001
    617, 92,  // en_SE -> en_150
    623, 85,  // en_SG -> en_001
    629, 85,  // en_SH -> en_001
    635, 92,  // en_SI -> en_150
    641, 92,  // en_SK -> en_150
    647, 85,  // en_SL -> en_001
    653, 85,  // en_SS -> en_001
    659, 85,  // en_SX -> en_001
    665, 85,  // en_SZ -> en_001
    671, 1167,  // en_Shaw -> root
    679, 85,  // en_TC -> en_001
    685, 85,  // en_TK -> en_001
    691, 85,  // en_TO -> en_001
    697, 85,  // en_TT -> en_001
    703, 85,  // en_TV -> en_001
    709, 85,  // en_TZ -> en_001
    715, 92,  // en_UA -> en_150
    721, 85,  // en_UG -> en_001
    727, 85,  // en_VC -> en_001
    733, 85,  // en_VG -> en_001
    739, 85,  // en_VU -> en_001
    745, 85,  // en_WS -> en_001
    751, 85,  // en_ZA -> en_001
    757, 85,  // en_ZM -> en_001
    763, 85,  // en_ZW -> en_001
    776, 769,  // es_AR -> es_419
    782, 769,  // es_BO -> es_419
    788, 769,  // es_BR -> es_419
    794, 769,  // es_BZ -> es_419
    800, 769,  // es_CL -> es_419
    806, 769,  // es_CO -> es_419
    812, 769,  // es_CR -> es_419
    818, 769,  // es_CU -> es_419
    824, 769,  // es_DO -> es_419
    830, 769,  // es_EC -> es_419
    836, 769,  // es_GT -> es_419
    842, 769,  // es_HN -> es_419
    848, 769,  // es_JP -> es_419
    854, 769,  // es_MX -> es_419
    860, 769,  // es_NI -> es_419
    866, 769,  // es_PA -> es_419
    872, 769,  // es_PE -> es_419
    878, 769,  // es_PR -> es_419
    884, 769,  // es_PY -> es_419
    890, 769,  // es_SV -> es_419
    896, 769,  // es_US -> es_419
    902, 769,  // es_UY -> es_419
    908, 769,  // es_VE -> es_419
    914, 1167,  // ff_Adlm -> root
    922, 1167,  // ff_Arab -> root
    930, 1167,  // ha_Arab -> root
    938, 371,  // hi_Latn -> en_IN
    946, 1167,  // iu_Latn -> root
    954, 1167,  // kaa_Latn -> root
    963, 1167,  // kk_Arab -> root
    971, 1167,  // kok_Latn -> root
    980, 1167,  // ks_Deva -> root
    988, 1167,  // ku_Arab -> root
    996, 1167,  // kxv_Deva -> root
    1005, 1167,  // kxv_Orya -> root
    1014, 1167,  // kxv_Telu -> root
    1023, 1167,  // ky_Arab -> root
    1031, 1167,  // ky_Latn -> root
    1039, 1167,  // ml_Arab -> root
    1047, 1167,  // mn_Mong -> root
    1055, 1167,  // mni_Mtei -> root
    1064, 1167,  // ms_Arab -> root
    1072, 1078,  // nb -> no
    1075, 1078,  // nn -> no
    1081, 1078,  // no_NO -> no
    1087, 1167,  // pa_Arab -> root
    1095, 1149,  // pt_AO -> pt_PT
    1101, 1149,  // pt_CH -> pt_PT
    1107, 1149,  // pt_CV -> pt_PT
    1113, 1149,  // pt_FR -> pt_PT
    1119, 1149,  // pt_GQ -> pt_PT
    1125, 1149,  // pt_GW -> pt_PT
    1131, 1149,  // pt_LU -> pt_PT
    1137, 1149,  // pt_MO -> pt_PT
    1143, 1149,  // pt_MZ -> pt_PT
    1155, 1149,  // pt_ST -> pt_PT
    1161, 1149,  // pt_TL -> pt_PT
    1172, 1167,  // sat_Deva -> root
    1181, 1167,  // sd_Deva -> root
    1189, 1167,  // sd_Khoj -> root
    1197, 1167,  // sd_Sind -> root
    1205, 1167,  // shi_Latn -> root
    1214, 1167,  // so_Arab -> root
    1222, 1167,  // sr_Latn -> root
    1230, 1167,  // suz_Sunu -> root
    1239, 1167,  // sw_Arab -> root
    1247, 1167,  // tg_Arab -> root
    1255, 1167,  // ug_Cyrl -> root
    1263, 1167,  // uz_Arab -> root
    1271, 1167,  // uz_Cyrl -> root
    1279, 1167,  // vai_Latn -> root
    1288, 1167,  // wo_Arab -> root
    1296, 1167,  // yo_Arab -> root
    1304, 1167,  // yue_Hans -> root
    1313, 1167,  // zh_Hant -> root
    1332, 1321,  // zh_Hant_MO -> zh_Hant_HK
};


#endif  // INCLUDED_FROM_URESBUND_CPP
